In [3]:
import pandas as pd
import os

In [24]:
data_types = {'Fiscal Year': int,
              'Employer': str,
              'Initial Approvals': str,
              'Initial Denials': str,
              'Continuing Approvals': str,
              'Continuing Denials': str,
              'NAICS': str,
              'Tax ID': str,
              'State': str,
              'City': str,
              'ZIP': str}

directory = 'data/h1b'
h1b_df = pd.DataFrame()
for file in os.listdir(directory):
    temp_df = pd.read_csv(os.path.join(directory, file), header=0, dtype=data_types)
    h1b_df = h1b_df.append(temp_df)

In [47]:
approvals = pd.DataFrame()
approvals['InitialApprovals'] = h1b_df.groupby('Employer')['Initial Approvals'].sum()
approvals['ContinuingApprovals'] = h1b_df.groupby('Employer')['Continuing Approvals'].sum()
approvals['TotalApprovals'] = approvals['InitialApprovals'] + approvals['ContinuingApprovals']

In [48]:
h1b_df[h1b_df['Employer'] == 'UNIVERSITY OF CALIFORNIA DAVIS']

,Fiscal Year,Employer,Initial Approvals,Initial Denials,Continuing Approvals,Continuing Denials,NAICS,Tax ID,State,City,ZIP
65136,2009,UNIVERSITY OF CALIFORNIA DAVIS,99,1,161,2,61,6494,CA,DAVIS,95616
53571,2013,UNIVERSITY OF CALIFORNIA DAVIS,82,0,87,0,61,6494,CA,DAVIS,95616
39163,2016,UNIVERSITY OF CALIFORNIA DAVIS,1,0,0,0,61,6494,CA,DAVIS,95616
54086,2018,UNIVERSITY OF CALIFORNIA DAVIS,54,0,64,1,61,6494,CA,DAVIS,95616
54087,2018,UNIVERSITY OF CALIFORNIA DAVIS,1,0,0,0,61,3649,CA,DAVIS,95616
45511,2019,UNIVERSITY OF CALIFORNIA DAVIS,60,1,51,5,61,6494,CA,DAVIS,95616